### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sosop112** [De-eloper/RAT-Crypting-Spreading-Tools#1]
please i will need your service .. let me know if we can talk on telegrem or icq

**Comment by De-eloper** [comment]
Hey, what do you need help with? let me know and I can see if I can help you with it

**Comment by sosop112** [comment]
i need you to help me set up a  rat for me and also crypter . i dont mind paying you for your time and your work . ASYNCRAT is the name please drop your telegram so that we can talk at real time . please

**Comment by De-eloper** [comment]
I dont provide any paid service, setting up rat is simple and you can port forward easily with playit.gg if you want that check youtube for videos. try ask other people for crypting, its hard to get good crypts for free..

**Comment by sosop112** [comment]
that is why i want you to help me i have been failing in the setting up of this virus and crypter i have been scammed by different seller please help even if it is for free ..  or i donate to any charity of your choice

**Comment by De-eloper** [comment]
Contact me by Discord, Developer#2448
I can try help set up for you

**Comment by sosop112** [comment]
thank you so much i just did . i will wait for you to accept thanks
